
Metrics/MethodLength:
  Enabled: false

Style/MethodDefParentheses:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
